// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getSnapshot: () => typedError<Snapshot, AppError>(__TAURI_INVOKE("get_snapshot")),
	refreshIndex: () => typedError<Snapshot, AppError>(__TAURI_INVOKE("refresh_index")),
	getTranscript: (id: string) => typedError<Transcript, AppError>(__TAURI_INVOKE("get_transcript", { id })),
	openSessionSource: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_session_source", { id })),
	getEvents: (id: string, offset: number, search: string) => typedError<EventPage, AppError>(__TAURI_INVOKE("get_events", { id, offset, search })),
	saveSources: (sources: Source[]) => typedError<null, AppError>(__TAURI_INVOKE("save_sources", { sources })),
	getPreferences: () => typedError<Preferences, AppError>(__TAURI_INVOKE("get_preferences")),
	savePreferences: (preferences: Preferences) => typedError<Preferences, AppError>(__TAURI_INVOKE("save_preferences", { preferences })),
	getCatalog: (request: CatalogRequest) => typedError<CatalogPayload, AppError>(__TAURI_INVOKE("get_catalog", { request })),
	saveCatalog: (payload: CatalogPayload) => typedError<null, AppError>(__TAURI_INVOKE("save_catalog", { payload })),
	getAccounts: () => typedError<Accounts, AppError>(__TAURI_INVOKE("get_accounts")),
	refreshAccount: (agent: Agent) => typedError<AccountStatus, AppError>(__TAURI_INVOKE("refresh_account", { agent })),
	saveToken: (agent: Agent, token: string | null) => typedError<null, AppError>(__TAURI_INVOKE("save_token", { agent, token })),
	exportFile: (filename: string, content: string) => typedError<boolean, AppError>(__TAURI_INVOKE("export_file", { filename, content })),
	exportSession: (id: string) => typedError<boolean, AppError>(__TAURI_INVOKE("export_session", { id })),
};

/** Events */
export const events = {
	accountsChanged: makeEvent<AccountsChanged>("accounts-changed"),
	indexChanged: makeEvent<IndexChanged>("index-changed"),
};

/* Types */
export type AccountStatus = {
	agent: Agent,
	usage: AccountUsage | null,
	error: AppError | null,
	lastAttempt: number,
	nextRefreshAt: number,
};

export type AccountUsage = {
	accountKey: string,
	plan: string | null,
	updatedAt: number,
	source: string,
	windows: QuotaSample[],
	balances: Balance[],
};

export type Accounts = {
	accounts: AccountStatus[],
	samples: QuotaSample[],
};

export type AccountsChanged = null;

export type Agent = "codex" | "claude" | "opencode" | "pi" | "grok" | "antigravity";

export type AppError = { kind: "io"; message: string } | { kind: "database"; message: string } | { kind: "invalidData"; message: string } | { kind: "notFound"; message: string } | { kind: "credentials"; message: string } | { kind: "network"; message: string } | { kind: "unauthorized"; message: string } | { kind: "rateLimited"; message: string } | { kind: "unsupported"; message: string } | { kind: "internal"; message: string };

export type Balance = {
	label: string,
	used: number | null,
	limit: number | null,
	remaining: number | null,
	unit: string,
	unlimited: boolean,
};

export type CatalogPayload = {
	json: string,
	updatedAt: number,
	source: CatalogSource,
	warning: AppError | null,
};

export type CatalogRequest = "stored" | "refresh" | "bundled";

export type CatalogSource = "bundled" | "cached" | "network";

export type EventKind = "user" | "assistant" | "thinking" | "tool" | "compaction";

export type EventPage = {
	events: SessionEvent[],
	offset: number,
	total: number,
	matches: number[],
};

export type IndexChanged = null;

export type Preferences = {
	theme: Theme,
	savedModels: string[],
	sidebarCollapsed: boolean,
};

export type QuotaSample = {
	agent: Agent,
	accountKey: string | null,
	bucket: string,
	label: string,
	usedPercent: number | null,
	windowMinutes: number,
	resetsAt: number | null,
	timestamp: number,
	source: string,
};

export type Session = {
	id: string,
	agent: Agent,
	title: string,
	cwd: string,
	project: string,
	model: string,
	startedAt: number,
	updatedAt: number,
	messages: number,
	turns: number,
	compactions: number,
	tokens: Tokens,
	usage: Usage[],
	tools: ToolStats[],
	limits: QuotaSample[],
	sourcePath: string,
	parentId: string | null,
	warnings: string[],
};

export type SessionEvent = {
	id: string,
	kind: EventKind,
	timestamp: number,
	text: string,
	model: string,
	tool: string | null,
	output: string | null,
	durationMs: number | null,
	failed: boolean | null,
};

export type Snapshot = {
	sessions: Session[],
	sources: SourceStatus[],
	scanning: boolean,
};

export type Source = {
	agent: Agent,
	path: string,
	enabled: boolean,
};

export type SourceStatus = {
	source: Source,
	available: boolean,
	sessions: number,
	issues: string[],
};

export type Theme = "dark" | "light" | "system";

export type TimelineEvent = {
	index: number,
	kind: EventKind,
	timestamp: number,
	durationMs: number | null,
	tool: string | null,
	failed: boolean | null,
};

export type Tokens = {
	input: number,
	cacheRead: number,
	cacheWrite: number,
	output: number,
	reasoning: number,
};

export type ToolStats = {
	name: string,
	calls: number,
	failures: number,
	completed: number,
	timed: number,
	durationMs: number,
};

export type Transcript = {
	session: Session,
	timeline: TimelineEvent[],
};

export type Usage = {
	timestamp: number,
	model: string,
	provider: string,
	tokens: Tokens,
	reportedCost: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

